# Generated by Django 4.1.3 on 2022-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_item_prix_reduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.CharField(choices=[('L', 'Legumes'), ('F', 'Fruits'), ('C', 'Cereales')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Secondary'), ('P', 'Primary'), ('D', 'Danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
