# Generated by Django 4.1.3 on 2022-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_item_categorie_item_description_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='tt.png', upload_to='static/images'),
        ),
    ]
